### ISSUE TITLE
[Idea] ok well afew really

### ISSUE THREAD

**Issue by kurokuno** [gr8pefish/IronBackpacks#1]
1. when iron chests is installed maybe try to integrate them into the backpack recipie

2. maybe a barrel backpack similar to jabba barrels it will hold large numbers of a single item but nothing else

3.i noticed you had accepted the idea of a furnace backpack so maybe a Crafting Grid upgrade too ? 

just afew ideas i had no real reason for you to accept them other than that i think they would be fun =D

**Comment by gr8pefish** [comment]
Thanks for the ideas! Here are my thoughts.

1) I thought about this but probably won't integrate it as the balance for movable storage (i.e. a backpack) is fundamentally different than static storage (a chest), and so the recipes should be different.

2) A barrel backpack is on the ToDo list (I will update the MCF posting with a visible public ToDo soon).

3) I don't feel like a crafting upgrade fits will with the idea of a backpack, especially since there are already other great mods that accomplish it. (See iBench: https://github.com/sapient/iBench). For that matter, I am torn about whether to include a furnace upgrade or not, as I am not sure it fits with the idea of portable storage...

If you have any other other feedback or want to reply to this feel free, otherwise I am going to mark this issue as closed.

Thanks!
