### ISSUE TITLE
Feature Request: Mining Filter config

### ISSUE THREAD

**Issue by KindarConrath** [gr8pefish/IronBackpacks#113]
In case a mods resources haven't been added, or don't get detected, the ability to add them in a configuration would be very helpful. I realize that there is the manual filter addition in game, but it would be nice because some items *shouldn't* need to be added manually.

e.g. Right now things like redstone and lapis get picked up, but AE2s Certus and Charged Certus don't.

**Comment by gr8pefish** [comment]
Thanks for the suggestion, it's a good one.

**Comment by xenoflot** [comment]
Please ignore this. I figured out it was just refilling the stack(s) I already had in inventory :-P

~~I'll hijack this to add that Coal and Flint aren't being picked up by the Mining Filter in 2.2.13 (current version in DW20 modpack at the time of writing). Since they're both extremely commonly acquired during mining, I'd like to see them added to the Mining Filter's default list.~~

Loving my shiny new diamond, compressing, auto-pickup backpack!  Thank you!
