### ISSUE TITLE
Shift-Right click with equipped quick deposit upgrade still not completely working

### ISSUE THREAD

**Issue by Dannerick** [gr8pefish/IronBackpacks#131]
#### Issue Description:
In the latest build of iron backpacks, many of the issues being seen with shift-right clicking on entities while wearing a quick deposit backpack have been cleared up. I have found that shift-right clicking on a rftools storage scanner with a storage module still does not work.

#### What happens:
When shift-right click on a storage scanner with a storage module, the effect appears to occur until you actually attempt to move the module or perform any other action. It looks like the action is only happening on the client side and does not actual get done on server-side. When you unequip the backpack everything occurs normally.

#### What you expected to happen:
Actions that need to occur with other mods when shift-right clicking on entities must be allowed to happen.

#### Steps to reproduce (important):

1. Wear quick deposit backpack
2. Shift-right click on storage scanner with storage module
3. Open inventory and move storage module to crafting grid
4. Linking info on module disappears
5. Unequip backpack
6. Shift-right click on storage scanner with storage module
7. Open inventory and move storage module to crafting grid
8. Link information persists correctly
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 2.2.2.20
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by Hazerd** [comment]
Now that you mention this, I've had a similar problem which seems to be the same bug.
When you shift+right-click a storage drawer the upgrades UI opens, but many of the slot numbers are messed up.
It's almost like you're visually in the drawer's UI, but actually interacting with your regular inventory (the last upgrade slot corresponds to your helmet slot, as an example)
Perhaps the client thinks it's in the correct UI, but the server thinks the user is in their normal inventory?

**Comment by gr8pefish** [comment]
Thanks for the bug report! I'm currently away from my computer, visiting family for Christmas, but I'll be sure to take a look at the issue when I return (just over a week from now).

@Hazerdous Is that a bug with Iron Backpacks, or just a separate bug in Storage Drawers that you are mentioning to help track down the source of my bug?

**Comment by Hazerd** [comment]
@gr8pefish It only occurs with a quick-deposit backpack equipped, and the effects seem to be similar to OP's issue (client thinks the action worked, server doesn't, resulting in a desync) so I'm assuming they're the same Iron Backpacks bug.

**Comment by gr8pefish** [comment]
Yeah, I'm just going to enforce an empty hand, there are just too many items that have special shift click functionality. I'll do that tomorrow.

**Comment by Hazerd** [comment]
That would fix some of this issue where you need to sneak+right-click a block with an item such as OP's issue, linking a storage module.
That wouldn't fix sneak+right-clicking things with an empty hand, such as the Storage Drawers or Botania's Ring of Loki (I don't think anybody uses that, it's just another example)

I think the only way to truly fix this is an addition to forge, at least a method on blocks/items to determine if sneak+right-click does anything
It might get weird with things like baubles (Ring of Loki) and equipped backpacks, not sure how those conflicts could be resolved.

Easier solution may be a hotkey to quick-deposit from an equipped backpack, so it's not using sneak+right-click in the first place. Unequipped backpacks can stay as-is, the item form is more compatible with everything.

**Comment by gr8pefish** [comment]
Alright, the way I hopefully solved this issue is be enforcing an empty hand in both the main and offhand. In addition, the backpack must have the upgrade *and* be able to deposit things. With these 3 checks now in, hopefully that may avoid all but the oddest corner cases.

@Hazerdous I tested it with Storage Drawers and it seems to work just fine, but maybe I'm missing out what exactly you meant. Could you clarify? Also, I totally forgot what the Ring of Loki does :P

That was my thought as well; if errors persist then I will implement a keybinding to fully solve the issue.

**Comment by gr8pefish** [comment]
Alright, so as it is probably (but not certainly) fixed, feel free to post again here if you encounter the error again and I will reopen the issue. Thanks!

**Comment by Hazerd** [comment]
Opened a dev workspace (of commit dfca1fac9eb49efd87b67a3b3e714abc17bb6051) just to test with the fix, the issue with Storage Drawers is still a thing.
It might be something weird Storage Drawers is doing with the inventory (something is clearly getting desynced), but the fact it only happens when the Quick Deposit event is fired leads me to believe that is the cause.

[I went ahead and made another video about this](https://youtu.be/auYQ-qd1Teg), and the results are surprising, the Quick Deposit event still happened even with a block in my hand (you can see the number on the drawer increase and the crafting tables in the backpack were removed)

**Comment by gr8pefish** [comment]
Huh, well thanks for the input. I think that since it's not used *that* much, I'm just going to make a hotkey for it and avoid all these oddities (as, like you said, there is no Forge method for "does special things on shift right click").

**Comment by gr8pefish** [comment]
So unfortunately the issues I ran into when trying to fix this are larger than expected. So what I've done is the following:

- Removed the ability to directly deposit via shift right click from an equipped backpack.
- Changed the unequipping code to be easier to use.

This means that it should now be quite simple to unequip, deposit, and then re-equip. 

While I would have preferred to make it work even when equipped, this issue has now taken more time than it is worth, and I need to fix other, more important things first. I may come back to it in the future, but for now I'm calling it closed.
