### ISSUE TITLE
Items can't be clicked in the inventory

### ISSUE THREAD

**Issue by Bedrockbreaker** [gr8pefish/IronBackpacks#172]
#### Issue Description:

When shift + (Using open backpack button when backpack is equipped) to open the configurable inventory, Any items in your hand cannot be interacted with.

#### What happens:

Items in your hand cannot be interacted with.

#### What you expected to happen:

I could do stuff with the items in my hand. Not have to switch my selected slot and re-open the configurable inventory GUI.

#### Steps to reproduce (important):

1. Put a configurable inventory upgrade (any) on any backpack
2. Hold at least one item and equip the backpack.
3. press shift + (open equipped backpack button)
4. Try to remove the held items from your inventory. Or anything with them really.

#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: 2.2.26
- Minecraft: 1.10
- Forge: 12.18.3.2297 (I think?)

#### My Solution that I thought of:

Add an if statement to check if the backpack is not equipped to lock the held slot. Otherwise, it should remain how it normally was.

**Comment by gr8pefish** [comment]
Thanks for the bug report!

Currently it this way so as to not allow dupe errors with other mods interacting with the configurable ghost slots, as that was a previous issue. Because of this, allowing the held item to be moved in the way you wanted is unfortunately not a perfect solution.

If you come up with a better idea, or in some other way show to me that it is a common and annoying enough issue I will reopen this, but I'm currently trying to fix some more pressing errors with my limited time.
