### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by xanderc2** [gr8pefish/IronBackpacks#18]
There is a duplication bug with your mod, i'd like to see it fixed because i like this mod, how to is in this video: https://www.dropbox.com/s/b4uy1zcl1t9vm61/bag%20bug%20dupe.mp4?dl=0

i also sent you a message on minecraft forum
thanks fore the great mod

regards
XanderT
youtube: http://www.youtube.com/xandercaget

**Comment by gr8pefish** [comment]
I'm having trouble duplicating this. Can you describing exactly what is happening and any other mods you have installed that may affect this? And the version of Iron Backpacks used here?

Thanks.
gr8pefish

**Comment by xanderc2** [comment]
that's the modpack: http://www.technicpack.net/modpack/technelogia-4-lite.613399
the version that i used on the video is: Iron Backpacks-1.7.10-1.0.4-universal
i removed it from the modpack cause of the bug, i'd like to add it again :)

Those are the steps:
Fill the bag with items
Put the bag on slot 1
Close and open it 2 times
Open the bag
Remove all items from the bag
Without close the bag press 1 while mouse is on an another empty inventory slot
Simply toss the bag While is still open (never close it!)
Pickup the bug
Done

i hope it helped, if still cant get it done dont esistate to contact me again
regards

**Comment by gr8pefish** [comment]
I haven't checked it in the old version, but I tried to do this in my dev. environment of my new in-progress version and it seemed to be bug-free with regards to moving the backpack in an unintended manner to cause a dupe.

Also, would you be interesting in contributing to a Italian localization file if I get one started for you?

**Comment by xanderc2** [comment]
Happy to know, may i have this version so i can test myself?

**Comment by gr8pefish** [comment]
It is a very unstable build at the moment, I will be sure to let you know when I release the beta though.

**Comment by TehNut** [comment]
I have a fix for this prepared for 1.7.10, I just need to know if it's safe to modify `ContainerBackpack.java` @gr8pefish

**Comment by gr8pefish** [comment]
Alright, a couple of things:

1) That change will fix the bug, but it isn't ideal; it will remove the ability to right click backpacks inside of other backpacks. @xanderc2 if you are fine with that then we can do a quick and dirty fix/build for you, or you can wait an indeterminate amount of time for the big update.

2) @TehNut regarding development in general: 

So the stable 1.0.4 build is the master branch, and that works all fine and everything. But then I wanted to get fancy and add a lot of features, a bit of which is shown in [this](https://www.youtube.com/watch?v=zJWFBbhLuow) video, but the essence is adding equip-able, render-able backpacks (and a handful of new upgrades). So I started these extensive changes on the dev branch, and made significant progress. However, it was still buggy when real life got in the way, and development has, obviously, stagnated a little bit. I have been working on it more recently, making another branch called devSweden, as I have to code on a different computer than normal while I am here in Sweden and I figured I could make a new branch to reflect that (but honestly devSweden is just a continuation of the dev branch, and the changes will eventually be merged to master anyway once it is more stable). 

Long story short, the most developed branch (devSweden) is nearing completion, but is not nearly as nice of code as the master branch, since I have done changes that, frankly, are over my head in terms of total understanding. This is fine, it is great actually, as I am learning a lot, I just have to go back and refactor afterwords (like what I did for the main branch for 1.0.4). 

So how does this affect you? You can push whatever you want to the 1.8 branch, but note that the more extensive changes you do the more interesting it may be to port some additions from 1.7, but if you feel as if it is worth it, if it will make future work significantly easier, then by all means go ahead and do it. For the 1.7.10 version, I would prefer if you didn't do much on the master branch, as the "real" source of cutting-edge development is on the devSweden branch and it is honestly not that far away from release. However, I am at that odd point where that code works, but I'm not entirely sure how anymore, I will have to go back and refactor/review at some point for sure. If you want to help on that branch feel free, but let me know because the code is gross and the issues/bugs that I am dealing with are barely documented anywhere (if at all). It just depends how involved you want to be with this.

**Comment by TehNut** [comment]
> it will remove the ability to right click backpacks inside of other backpacks

Did not realize that was even a thing. ~~I'll go ahead and re-add it.~~ Fixed.

> It just depends how involved you want to be with this.

I am free to help out as much (or as little) as you want.

**Comment by gr8pefish** [comment]
> I am free to help out as much (or as little) as you want.

Okay, then ideally I would like it to be something like this: 
1.8: You keep on doing you for the 1.8 changes. For example, expanding the usage of IBackpack (before a possible API) is great, I should have done that. All the minor changes (i.e. gradle files, minor cleanup) are helpful, as I simply don't have the knowledge to make it as clean as you do.

1.7.10: In all honesty you probably don't want to deal with the code as it is _right now_, but that may change in the future. I would like to personally backport some of the cleanup changes you did on the 1.8 branch, as that will help me learn why and how you did them. Other than that though, if you want to help out on that branch later we can decide that in the future when it is in a more workable state :P 

> Did not realize that was even a thing.

If you have any questions ever, just ask me!

**Comment by TehNut** [comment]
> If you have any questions ever, just ask me!

How crazy am I allowed to get with cleanup? :p

**Comment by gr8pefish** [comment]
Go crazy! If you do so I might not port everything back to 1.7, but it is
still helpful.

**Comment by gr8pefish** [comment]
Okay, so more updates:

@xanderc2 The bug seems to be fixed in the new version. You can still move the backpack using the number key (something that I do plan on fixing as well), but you cannot drop it, meaning you cannot duplicate the items. I also plan on releasing the new version later today! [Here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2331340-iron-backpacks)'s a link.

@TehNut I can't work on 2 versions at once, it is too much work, so you have mostly free reign on the 1.8 version, just don't stray too far from what I have done on the main 1.7 mod :) Once again, just ask me (it is hard because of the massive time difference between where we live, but we can make it work). Contact me via email or reddit message or here for a quick reply.

**Comment by TehNut** [comment]
I'm just going to be porting whatever is in `master` as well as doing cleanup.

**Comment by gr8pefish** [comment]
Perfect!

**Comment by xanderc2** [comment]
really thanks, downloading, is ever a pleasure to find an helpful dev :D

PS: if you have some mods in test phase that need to be sponsored on youtube or need ideas for mods feel free to ask :)
(i think you have my mail)

**Comment by gr8pefish** [comment]
No problem, thanks for appreciating it!

I only ask that you try and break my mod. My computer that I am working on right now is very weak, and so my testing hasn't been as thorough as I would like (testing at 6 fps is not very fun :P)

I may ask you to do a spotlight on this mod actually once I get this 1.2.x version bug-free and once I have added a couple more features. I think I have plenty of work to do on this mod alone, but if I somehow run out of ideas for modding I will let you know :)
