### ISSUE TITLE
[ Fix ] - [ Config Bugs ]

### ISSUE THREAD

**Issue by ghost** [gr8pefish/IronBackpacks#235]
#### Issue Description:

Problems with the in-game config, and problems with manipulating the physical config file manually and its in-game effects.

#### What happens:

In game config does not properly change the physical file associated with the behavior of the backpacks. When reloading the game the changes made are reverted. When you manipulate the physical config file, it does work though. However, only the removal of upgrades works, if you change the inventory space of the backpacks, and then start up the game, the back packs capacity will not change and will remain the same as how it originally was without any changes, despite the fact that the in-game config shows the custom values.

More specifically I changed the backpack capacity to as follows:
Basic: 9
IronStorage: 18
IronUpgrade: 9
GoldStorage: 27
GoldUpgrade: 18
DiamondStorage: 36
DiamondUpgrade: 27

None of the backpacks ever changed their capacity.

#### What you expected to happen:

What was expected was for the config system to function accordingly/appropriately.

#### Steps to reproduce (important):

1. Attempt to edit the in-game config, exit config, reopen config, see that the settings saved.
2. Restart game after step 1, and reopen game, see that the config reset/did not save.
3. Edit the config file manually (such as disabling upgrades and changing backpack capacity), discover that the upgrade disabling/enabling worked, but changing the capacity of the backpacks did not, despite the fact that in the config it now shows the custom capacity values set.
...

____
#### Affected Versions (Do *not* use "latest"):

- IronBackpacks: Beta - IronBackpacks-1.12.2-3.0.7-10.jar
- Minecraft: 1.12.2
- Forge: 14.23.3.2655
- Other Conflicting Mods (may be irrelevant to your issue):
I have tested the mod stand alone (even without Optifine), and in my mod pack, the issue still persists.

--------

I do hope this can be addressed/is verified as an issue to be fixed in the next Beta/Release 👍 :)

**Comment by TehNut** [comment]
Ah, we forgot to add the actual reloading subscription.

ie: 

https://github.com/WayofTime/BloodMagic/blob/389043dc64718f3443ea50182999aca8b1410d7a/src/main/java/WayofTime/bloodmagic/ConfigHandler.java#L28-L36

**Comment by SextupleTap** [comment]
Ahha ok, I "think" I also understand?

With the code:
"    @SubscribeEvent
    public static void onConfigChanged(ConfigChangedEvent.OnConfigChangedEvent event)
    {
        if (event.getModID().equals(BloodMagic.MODID))
        {
            ConfigManager.sync(event.getModID(), Config.Type.INSTANCE); // Sync config values
            MeteorConfigHandler.handleMeteors(false); // Reload meteors
        }
    }
(Edited/similarly recreated for iron backpacks since the code is for Blood magic...)
"

That code would allow the values corresponding to say the backpack capacity to actually be registered/synced with the config file and reload? Like the numeric values responsible for setting the backpacks capacity, which are modifiable by the config. Am I correct about this?

Also, why did the disabling and enabling of different backpack upgrades function fine, was that a different segment of the mods coding that functioned properly/was included, while the section of code responsible for the backpacks inventory space/capacity was forgotten?
