### ISSUE TITLE
Bad "interaction" with Roboticraft resulting in crash on launch

### ISSUE THREAD

**Issue by vrork** [gr8pefish/IronBackpacks#237]
Crashing on launch;
https://gist.github.com/vrork/c52f4e128eae3ab91a81a5369b917971

- IronBackpacks: 1.12.2-3.0.8-12
- Minecraft: 1.12.2
- Forge: 14.23.3.702
- Other Conflicting Mods (may be irrelevant to your issue): Roboticraft 0.10.3 (testing with prior versions atm)

**Comment by TehNut** [comment]
[This is the absolute most cancerous bit of code I have ever come across.](https://github.com/DomAmato/Robot/blob/master/src/main/java/com/dyn/robot/RegistrationHandler.java) This issue is 100% on their end.

**Comment by DomAmato** [comment]
wait so your code is causing a null pointer and its a problem on my end? lets be serious now

**Comment by ChloeDawn** [comment]
@DomAmato Your code is failing for the same reason you hardcode against vanilla instances [here](https://github.com/DomAmato/Robot/blob/fb9b6cf7c741781e8bc275057c9cbe64c238ec15/src/main/java/com/dyn/robot/RegistrationHandler.java#L63-L64). Until you can write your registry in a way that doesn't require actively avoiding those item classes, the problem is on your end.

**Comment by DomAmato** [comment]
I'm definitely not saying that the registry is perfect and there is probably a better way but the code that is failing is in iron backpacks on this line:
https://github.com/gr8pefish/IronBackpacks/blob/dev-1.12/src/main/java/gr8pefish/ironbackpacks/item/ItemUpgrade.java#L36

For some reason getUpgrade(stack) is returning null so your isNull() doesn't work because the object is null. Realistically checking that `backpackUpgrade == null || backpackUpgrade.isNull()` would prevent the crash.

If calling getDisplayName on the subitems returned by your mod item is causing a null pointer I don't think its fair to say that its my registry's fault.

**Comment by DomAmato** [comment]
alright i moved the registry creation into the post init phase and tested it along side the most recent master here and it didnt crash so hopefully that fixes all this
