### ISSUE TITLE
enhancement: "Do not Sort my backpack"

### ISSUE THREAD

**Issue by Ioandar** [gr8pefish/IronBackpacks#49]
Heya,

the 2.0.2 works nice for me. Is there a way to NOT have a backpacks Item positions sorted? I think it is happening with the restock upgrade (I use it for torches)

Like -> what currently is in slot 1 stays in slot 1. Just like normal chests. 

-> When I pipe/golem things in or out a normal chest the remaining things stay at their places. 
-> New Items will fill first stack of same type or get first free place thats free

crown would be the 'let 1 item of each restock stack stay in backpack' option like from logistics pipes. So even IF you use restock, your backpack stays tidy :)

or a seperate digging(cobble/dirt,pp) or mining(ores pp) folder in the backpack? I dont know, just ideas. I am new to this :)

**Comment by gr8pefish** [comment]
Yes, the restocking upgrade is sorting the backpack each time it picks something up. I will fix that so it isn't necessary, as well as doing the same on the other filtering upgrades.

I could let 1 of each item stay in the backpack, but since it pulls from anywhere in the backpack (because I won't automatically sort it), I don't see the point of leaving 1 item instead of taking all of them. If you disagree though, let me know why.

I do appreciate the suggestions though! I am always grateful for feedback, even if I don't decide to implement your ideas exactly as you state them. So feel free to continue to post ideas/suggestions/improvements/concerns/questions/comments/etc. and I will do my best to make this mod as useful as possible.

**Comment by Ioandar** [comment]
no worries, I was just throwing ideas. I am totally fine with that! Indeed its better the way you said.

you just grab what you think might work best for your mod :) Its awesome already and tyvm for your work!
