### ISSUE TITLE
Client SMP Crash

### ISSUE THREAD

**Issue by gr8pefish** [gr8pefish/IronBackpacks#54]
Log: https://paste.ee/r/H7GBh

**Comment by Cabdono** [comment]
Last thing i think i did was killing a mob in a nether portal and tried to pick up the drops, couldn't, backed away and crashed less than 5 seconds later, I had a backpack on, 2 inside, one with filters but the drops weren't filtered so no reason to pick them up, most of the times it happens when i'm near a nether portal.

**Comment by LilaCDolL** [comment]
Also having it crash on 1.7.10 when picking up items. only happens when i have a backpack with any filter upgrade nested in a backpack that is of equal or higher grade (basic, iron, gold, diamond). Eg. taking a diamond backpack putting advanced nesting and depth upgrade on it then taking a gold backpack and putting advanced filter on it. with the gold backpack in the diamond backpack picking up an item will cause the game to crash. However if you reverse the grade of the backpacks and take a lower grade backpack with nesting and depth and put a higher grade backpack with a filter on it everything seems to work fine. Eg. Iron backpack with advanced nesting and depth and gold backpack with advanced filter inside

**Comment by gr8pefish** [comment]
Just checked for 1.10, no issues there. I'm focusing on that version right now, but I will come back and fix this issue sometime soon.

**Comment by gr8pefish** [comment]
@LilaCDolL - I can't replicate this error using your example:
- Diamond backpack: advanced nesting and depth upgrade
- Gold backpack: advanced filter set to take in exactly smoothstone
- Put gold backpack in diamond backpack, equip the diamond backpack, pick up smoothstone, and it goes into the nested gold backpack, as it should.

If you could clarify on how to reproduce the error that would be much appreciated. Otherwise I will close this issue soon.

**Comment by gr8pefish** [comment]
No input, closing.
