### ISSUE TITLE
1.10.2 game crash when adding crafting upgrade 

### ISSUE THREAD

**Issue by LordHellscream** [gr8pefish/IronBackpacks#78]
Testing this with diamond backpack, have a mining upgrade and void upgrade, attempting to add crafting upgrade (full 3x3 grid) to it on the tinker construct craft station, when i picking the result item from the crafting it CTD, here is the log

http://pastebin.com/kmvQPk15

**Comment by LordHellscream** [comment]
After logging back in, the backpack have a weird invalid upgrade on it that i cannot remove, called "item.ironbackpacks.upgrade.recipe.name"

**Comment by LordHellscream** [comment]
when i created a new backpack and added the crafting upgrade again, it didn't crash but still getting a bad invalid upgrade. then later when i removed it (the crafting upgrade), then attempting to access the configure GUI, it froze the game and then crashed it

**Comment by gr8pefish** [comment]
The crash report you gave me indicates the error is one due to a rendering of the backpack on your back causing a crash, it doesn't have anything to do with the crafting. 

That being said, I don't know how you got the odd unnamed upgrade; could you perhaps give me steps to duplicate the error? I cannot do so in my own testing, adding the 3 upgrades causes no errors for me.

Also, were all the crashes client side, or was it ever a server crash?

**Comment by LordHellscream** [comment]
create a (storage emphasis) diamond bag (i got it from JEI), get a 3x3 crafting upgrade (btw, it may be better to call it compacting upgrade, which is really what it is, it was confusing for while to figure out how it works)

put them bag and upgrade on crafting grid, i did this just using regular vanilla crafting table, and grab the result. put the bag in action bar, shift-right click.

it reads item.ironbackpacks.upgrade.recipes.name
