### ISSUE TITLE
Equipped backpack reverted to previous inventory

### ISSUE THREAD

**Issue by clawdude13** [gr8pefish/IronBackpacks#83]
From out of no where my backpack inventory reverted back to a previous time and i empty the bag and try to un equipped it and did not get the backpack back. So i saved and quit and when i loaded the save i had the backpack equipped somehow. So i un equipped the backpack and made  new one and equipped it and was able to acess it and take it on and off but as soon as I save and quit i lose the new backpack and revert back to previous backpack.I am using 2.2.4 version of iron backpacks on 1.10.2

**Comment by gr8pefish** [comment]
_I know it is likely difficult, but any more details about what caused this would help immensely._

For example, what exactly were you doing when the backpack reverted? What were you doing before that? I really want to fix this bug, but it's so inconsistent I can't replicate it, which makes things much harder.

Moving forward, if I can't fix the source of the error soon, I will at least implement a command to unequip the backpack (and have it stay off) so that your world is usable again asap.

**Comment by gr8pefish** [comment]
I ask you to still reply, but in [Issue #62](https://github.com/gr8pefish/IronBackpacks/issues/62), as that is the same issue (and hence why I am closing this one).
