### ISSUE TITLE
Shift clicking recipes isn't possible currently

### ISSUE THREAD

**Issue by misterfixit** [gr8pefish/IronBackpacks#84]
#### Issue Description:

The upgrade page for iron, gold, and diamond backpacks doesn't have the JEI fill recipe button so shift clicking the recipe isn't possible.
#### What happens:

No Jei fill recipe button
#### What you expected to happen:

The + button to fill the recipe
#### Steps to reproduce (important):
1. 
2. 
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- IronBackpacks: 2.2.5
- Minecraft: 1.10.2
- Forge: 2088

**Comment by gr8pefish** [comment]
I currently do some fancy things (internally) with the recipe for upgrading backpacks, it is a custom recipe so that the new, upgraded backpack keeps all of the items, upgrades, etc. from the previous backpack. Since backpacks aren't upgraded _that_ often I haven't written a custom JEI handler to account for this, but as this was brought up I will work on it at some point (but note that it is a low priority for me due to a mix of decent implementation complexity and minimal usefulness).

**Comment by misterfixit** [comment]
It's more a quality of life enchantment, just threw me off when I tried to shift click the recipe. Appreciate you working on it.

**Comment by gr8pefish** [comment]
One year later...I don't think this is high enough priority, especially as I have the rewrite to focus on. You never mass produce upgraded backpacks, so it's an acceptable lack of a feature.
