### ISSUE TITLE
1.10.2 Crash. Horrible crash.

### ISSUE THREAD

**Issue by LeFiend** [gr8pefish/IronBackpacks#90]
#### Issue Description:

Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.
#### What happens:

Minecraft _closes_ (or crashes) everytime I try to put any item on any crafting menu(On the crafting table, or my own 4item crafting table.
#### What you expected to happen:

To be able to craft normally.
#### Steps to reproduce (important):
1. 
2. 
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- IronBackpacks: 2.2.7
- Minecraft: 1.10.2
- Forge: 1.10.2
  [crash-2016-10-29_16.30.19-client.txt](https://github.com/gr8pefish/IronBackpacks/files/559838/crash-2016-10-29_16.30.19-client.txt)

**Comment by gr8pefish** [comment]
Actually fill out the template, it's there for a reason. I can't help you with this insufficient bug report.

**Comment by Traverse-Joe** [comment]
I actually have the same Crash 
lemme post my crashlog for you @gr8pefish 
http://pastebin.com/6qcCRGiL

**Comment by p455w0rd** [comment]
just submitted a PR to fix this #93

**Comment by gr8pefish** [comment]
Thanks! I've been away from my computer all day, I'll check it out when I
get home late tonight.

**Comment by p455w0rd** [comment]
Just so everyone knows, this is technically a bug on JEI's side. As far as I can tell, it simply due to load order. JEI doesn't specify "before:*" so it's not forcing itself load before everything else. The odd thing is that ironbackpacks is the only mod to show up causing this error. But the workaround it would seem is to just force your mod to load after JEI at least for now. Also, from what I have heard this only happens in JEI 3.13+
