### ISSUE TITLE
"Needed" Option - Config for Disable Wearing

### ISSUE THREAD

**Issue by SirWyld** [gr8pefish/IronBackpacks#97]
As the title states, I'm fairly urgently needing a config option that disables the ability for a player to wear the backpack.

I love the mod, it's expandable and awesome on many levels. However, there are multiple methods to dupe the backpack on a server when it interacts with other mods. It all comes down to how various mods see the player and their inventory. A classic example is various gravestone mods, but it's not limited there. After working on it for a few days, and testing with about 12 people, the one option that could get around all issues would be to optionally disable the wearing.

<3

**Comment by gr8pefish** [comment]
Sure, I can do that tonight when I get home.

**Comment by necrogami** [comment]
Also with this could it be possible to check initially at least if they have one in slot and it can either 1 time remove or 2 kick it out of their slot and into inventory/ground depending on inventory space.

**Comment by gr8pefish** [comment]
The way I was thinking of going about it to preserve backwards
compatibility would be to still allow unequipping, and just explicitly
disable equipping. That would be easy for me to implement, hence why I
thought of this. Would that address your concerns?

**Comment by SirWyld** [comment]
That's a smooth solution.

**Comment by necrogami** [comment]
That is perfect!

**Comment by Mattabase** [comment]
I dig the solution

**Comment by gr8pefish** [comment]
Okay, so I implemented the config option to disable the equipping of backpacks (along with a couple other config tweaks, see the commit message above for more details). A new version containing those changes is now up on CurseForge. 

Now, while I am totally fine with the config option for disabling the equipping of a backpack (as a catch-all for inter-mod nonsense), I think that the equipping/rendering on the player is a cool aspect of the mod and I would like to preserve it. 
With that in mind, I would appreciate it if you could report duplication methods on this bug tracker. While I don't intend to catch _all_ the methods, I would like to natively circumvent the common methods of doing so, something that I think that is feasible (for example, in 1.7.10 OpenBlocks' graves and other similar graves mods work just fine due to a little code tweaking on my part). 

Thanks!

**Comment by Mattabase** [comment]
Thanks for the change. Yeah Dupes happened with Tomb Many Graves. Though sponge was being used so I would need to test it outside of sponge to confirm it.

**Comment by gr8pefish** [comment]
FYI: I pushed out a new version that tweaks a lot of default values, simply to balance the mod better. Some of these changes were via the config file, so I recommend you delete the config and let it regenerate when updating to 2.2.11. After it regens you can once again alter the line so it is allowEquipping=false, that way you get the balance modifications I just did as well as your modpack config change to disable equipping. Enjoy!

**Comment by gr8pefish** [comment]
Oh by the way y'all, I recently pushed out a new version that adds compatibility with the recent version of TombManyGraves for equipped backpacks. It wasn't just hot air when I said I would make it reliably function even between mods, it just takes a while :P

**Comment by Mattabase** [comment]
Awesome! Love to see that compatibility is on your list of things to do =)
